version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dobbe-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
